name: Multi-Branch Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "Building and testing for main branch"
          # Add your build and test commands here
        elif [[ "${{ github.ref }}" == "refs/heads/java" ]]; then
          echo "Building and testing for develop branch"
          # Add your build and test commands here
        else
          echo "Building and testing for other branches"
          # Add your build and test commands here
        fi
