name: deploy
on:
  push:
      branches: [ master, java, python ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
            
      - name: Use Node.js
      - name: echo
        run: echo "Hello World"
      - name: 'Run az commands on branch 1'
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
           echo "Hello World"
      - name: 'Run az commands on branch 2'
        if: ${{ github.ref == 'refs/heads/java' }}
        run: |
            echo  "Hello World" 
      - name: 'Run az commands on branch 3'
        if: ${{ github.ref == 'refs/heads/python' }}
        run: |
           echo "hello World"
