name: deploy
on:
  push:
    branches: [java, python]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
            
      - name: Use Node.js
        run: echo "Using Node.js"
      
      - name: echo
        run: echo "Hello World"
      
      - name: 'Run az commands on branch 1'
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "Running az commands for branch master"
          # Add your actual Azure CLI commands here
          
      - name: 'Run az commands on branch 2'
        if: ${{ github.ref == 'refs/heads/java' }}
        run: |
          echo "Running az commands for branch java"
          # Add your actual Azure CLI commands here
          
      - name: 'Run az commands on branch 3'
        if: ${{ github.ref == 'refs/heads/python' }}
        run: |
          echo "Running az commands for branch python"
          # Add your actual Azure CLI commands here
