name: Multi-Branch Workflow

on:
  push:
    branches:
      - master
      - react
      - java
      - python

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: multibranch result
      run: |
        echo "helloword"
        
  java:
    name: Deploy to Development Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: multibranch result
        run: |
          echo "helloword"
        
      
    
