name: Multibranch Workflow

on:
  push:
    branches:
      - master
      - python/*

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      

      - name: Install dependencies
        run: echo "Hello World"

      

  deploy_to_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/python/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add deployment steps for staging here

  deploy_to_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add deployment steps for production here
