name: Multi-Branch Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: multibranch result
      run: |
        echo "helloword"
    
